name = "inchive-landing"
main = "worker.js"
compatibility_date = "2023-12-01"

# Custom domain (requires inchive.com to be added to Cloudflare)
routes = [
  { pattern = "inchive.com", custom_domain = true },
  { pattern = "www.inchive.com", custom_domain = true }
]

# Development variables (Replace with `wrangler secret put` for production)
[vars]
ADMIN_PASSWORD = "change_this_password_immediately"

[[kv_namespaces]]
binding = "INCHIVE_WAITLIST"
id = "9572e6b8c13d44b188a40ab495c9ea1c"


